INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:45:27] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:45:30] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:46:22] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:46:25] "[37mGET /about HTTP/1.1[0m" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Beatrice Chatuwa\Documents\nd064_course_1-1\project\techtrends\app.py", line 71, in create
    app.logger.info('{} article is created'.format(str(title)))
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:46:27] "[35m[1mGET /create HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:46:33] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:47:26] "[37mGET /healthz HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:47:41] "[37mGET /metrics HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:50:55] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:51:02] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:51:25] "[37mGET /2 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:54:34] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:54:51] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:58:26] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:58:27] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:58:28] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 11:58:31] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:07:18] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:07:19] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:07:20] "[37mGET /2 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:07:23] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:44:37] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:44:55] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:45:07] "[37mGET /about HTTP/1.1[0m" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Beatrice Chatuwa\Documents\nd064_course_1-1\project\techtrends\app.py", line 72, in create
    app.logger.info('%s article is created', title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:45:11] "[35m[1mGET /create HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:45:14] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:45:21] "[37mGET /6 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:45:23] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:51:52] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:51:56] "[37mGET /about HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:51:58] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:52:00] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:52:02] "[37mGET / HTTP/1.1[0m" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Beatrice Chatuwa\Documents\nd064_course_1-1\project\techtrends\app.py", line 72, in create
    app.logger.info("%s article is created", title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:52:05] "[35m[1mGET /create HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:52:16] "[37mGET /4 HTTP/1.1[0m" 200 -
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:26] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:30] "[37mGET /1 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:32] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:34] "[37mGET /6 HTTP/1.1[0m" 200 -
ERROR:app:Exception on /create [GET]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Beatrice Chatuwa\Documents\nd064_course_1-1\project\techtrends\app.py", line 72, in create
    app.logger.info("%s article is created", title)
UnboundLocalError: local variable 'title' referenced before assignment
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:39] "[35m[1mGET /create HTTP/1.1[0m" 500 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 12:55:42] "[37mGET /about HTTP/1.1[0m" 200 -
INFO:werkzeug: * Restarting with windowsapi reloader
INFO:werkzeug: * Restarting with windowsapi reloader
 WARNING werkzeug2021-08-18 13:22:38,240 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-18 13:22:38,256 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 WARNING werkzeug2021-08-18 13:24:14,534 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-18 13:24:14,534 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
INFO:werkzeug: * Running on http://0.0.0.0:3111/ (Press CTRL+C to quit)
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:35] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:38] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:42] "[37mGET /3 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:50] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:52] "[37mGET /about HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:54] "[37mGET / HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:29:58] "[37mGET /6 HTTP/1.1[0m" 200 -
INFO:werkzeug:192.168.1.154 - - [18/Aug/2021 13:30:00] "[37mGET /about HTTP/1.1[0m" 200 -
 WARNING werkzeug2021-08-20 19:21:26,246 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-20 19:21:27,268 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 INFO app2021-08-20 19:23:01,207 : The Index page is retrieved
 INFO werkzeug2021-08-20 19:23:03,169 : 192.168.1.154 - - [20/Aug/2021 19:23:03] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:23:03,725 : 192.168.1.154 - - [20/Aug/2021 19:23:03] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 19:23:08,889 : Article <sqlite3.Row object at 0x0000015BCE571B30> retrieved!
 INFO werkzeug2021-08-20 19:23:09,080 : 192.168.1.154 - - [20/Aug/2021 19:23:09] "GET /5 HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:23:09,171 : 192.168.1.154 - - [20/Aug/2021 19:23:09] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 ERROR app2021-08-20 19:23:11,608 : Exception on /create [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 83, in create
    app.logger.info("%s article is created", title)
UnboundLocalError: local variable 'title' referenced before assignment
 INFO werkzeug2021-08-20 19:23:11,634 : 192.168.1.154 - - [20/Aug/2021 19:23:11] "[35m[1mGET /create HTTP/1.1[0m" 500 -
 INFO app2021-08-20 19:23:16,636 : The About Us page is retrieved
 INFO werkzeug2021-08-20 19:23:16,740 : 192.168.1.154 - - [20/Aug/2021 19:23:16] "GET /about HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:23:16,832 : 192.168.1.154 - - [20/Aug/2021 19:23:16] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 19:23:18,433 : The Index page is retrieved
 INFO werkzeug2021-08-20 19:23:18,459 : 192.168.1.154 - - [20/Aug/2021 19:23:18] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:23:18,549 : 192.168.1.154 - - [20/Aug/2021 19:23:18] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 ERROR app2021-08-20 19:23:20,132 : Exception on /create [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 83, in create
    app.logger.info("%s article is created", title)
UnboundLocalError: local variable 'title' referenced before assignment
 INFO werkzeug2021-08-20 19:23:20,181 : 192.168.1.154 - - [20/Aug/2021 19:23:20] "[35m[1mGET /create HTTP/1.1[0m" 500 -
 INFO app2021-08-20 19:23:32,120 : Article <sqlite3.Row object at 0x0000015BCE67B190> retrieved!
 INFO werkzeug2021-08-20 19:23:32,147 : 192.168.1.154 - - [20/Aug/2021 19:23:32] "GET /6 HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:23:32,235 : 192.168.1.154 - - [20/Aug/2021 19:23:32] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 WARNING werkzeug2021-08-20 19:43:14,376 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-20 19:43:14,476 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 INFO app2021-08-20 19:43:30,430 : The Index page is retrieved
 INFO werkzeug2021-08-20 19:43:30,614 : 192.168.1.154 - - [20/Aug/2021 19:43:30] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:43:30,772 : 192.168.1.154 - - [20/Aug/2021 19:43:30] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO werkzeug2021-08-20 19:43:34,727 : 192.168.1.154 - - [20/Aug/2021 19:43:34] "GET /create HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:43:34,827 : 192.168.1.154 - - [20/Aug/2021 19:43:34] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 19:43:47,059 : The Index page is retrieved
 INFO werkzeug2021-08-20 19:43:47,099 : 192.168.1.154 - - [20/Aug/2021 19:43:47] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 19:43:47,370 : 192.168.1.154 - - [20/Aug/2021 19:43:47] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 ERROR app2021-08-20 19:43:53,561 : Exception on /6 [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 56, in post
    app.logger.info("Article %s retrieved!",post.html)
AttributeError: 'sqlite3.Row' object has no attribute 'html'
 INFO werkzeug2021-08-20 19:43:53,610 : 192.168.1.154 - - [20/Aug/2021 19:43:53] "[35m[1mGET /6 HTTP/1.1[0m" 500 -
 WARNING werkzeug2021-08-20 19:54:57,015 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-20 19:54:58,786 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 WARNING werkzeug2021-08-20 20:19:34,797 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-20 20:19:35,354 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 INFO app2021-08-20 20:19:49,567 : The Index page is retrieved
 INFO werkzeug2021-08-20 20:19:50,602 : 192.168.1.154 - - [20/Aug/2021 20:19:50] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 20:19:51,262 : 192.168.1.154 - - [20/Aug/2021 20:19:51] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 20:19:59,872 : The About Us page is retrieved
 INFO werkzeug2021-08-20 20:20:00,016 : 192.168.1.154 - - [20/Aug/2021 20:20:00] "GET /about HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 20:20:00,488 : 192.168.1.154 - - [20/Aug/2021 20:20:00] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO werkzeug2021-08-20 20:20:04,431 : 192.168.1.154 - - [20/Aug/2021 20:20:04] "GET /create HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 20:20:04,602 : 192.168.1.154 - - [20/Aug/2021 20:20:04] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 20:20:12,614 : The Index page is retrieved
 INFO werkzeug2021-08-20 20:20:13,219 : 192.168.1.154 - - [20/Aug/2021 20:20:13] "GET / HTTP/1.1" 200 -
 INFO app2021-08-20 20:20:13,221 : The Index page is retrieved
 INFO werkzeug2021-08-20 20:20:13,421 : 192.168.1.154 - - [20/Aug/2021 20:20:13] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 20:20:13,724 : 192.168.1.154 - - [20/Aug/2021 20:20:13] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 ERROR app2021-08-20 20:20:20,173 : Exception on /6 [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 56, in post
    app.logger.info("Article %s retrieved!",title)
NameError: name 'title' is not defined
 INFO werkzeug2021-08-20 20:20:20,434 : 192.168.1.154 - - [20/Aug/2021 20:20:20] "[35m[1mGET /6 HTTP/1.1[0m" 500 -
 ERROR app2021-08-20 20:20:27,968 : Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 56, in post
    app.logger.info("Article %s retrieved!",title)
NameError: name 'title' is not defined
 INFO werkzeug2021-08-20 20:20:27,995 : 192.168.1.154 - - [20/Aug/2021 20:20:27] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
 ERROR app2021-08-20 20:20:38,868 : Exception on /1 [GET]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python36\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python36\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 56, in post
    app.logger.info("Article %s retrieved!",title)
NameError: name 'title' is not defined
 INFO werkzeug2021-08-20 20:20:38,946 : 192.168.1.154 - - [20/Aug/2021 20:20:38] "[35m[1mGET /1 HTTP/1.1[0m" 500 -
 WARNING werkzeug2021-08-20 21:20:37,076 :  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 INFO werkzeug2021-08-20 21:20:37,482 :  * Running on http://192.168.1.154:3111/ (Press CTRL+C to quit)
 INFO app2021-08-20 21:20:46,256 : The Index page is retrieved
 INFO werkzeug2021-08-20 21:20:46,939 : 192.168.1.154 - - [20/Aug/2021 21:20:46] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:20:47,491 : 192.168.1.154 - - [20/Aug/2021 21:20:47] "GET /static/css/main.css HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:20:48,746 : 192.168.1.154 - - [20/Aug/2021 21:20:48] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
 INFO app2021-08-20 21:20:51,991 : Article 6 retrieved!
 INFO werkzeug2021-08-20 21:20:52,023 : 192.168.1.154 - - [20/Aug/2021 21:20:52] "GET /6 HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:20:52,103 : 192.168.1.154 - - [20/Aug/2021 21:20:52] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 21:20:58,110 : Article 1 retrieved!
 INFO werkzeug2021-08-20 21:20:58,134 : 192.168.1.154 - - [20/Aug/2021 21:20:58] "GET /1 HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:20:58,246 : 192.168.1.154 - - [20/Aug/2021 21:20:58] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 21:21:02,319 : Article 4 retrieved!
 INFO werkzeug2021-08-20 21:21:02,351 : 192.168.1.154 - - [20/Aug/2021 21:21:02] "GET /4 HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:21:02,463 : 192.168.1.154 - - [20/Aug/2021 21:21:02] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 21:21:06,475 : The About Us page is retrieved
 INFO werkzeug2021-08-20 21:21:06,539 : 192.168.1.154 - - [20/Aug/2021 21:21:06] "GET /about HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:21:06,635 : 192.168.1.154 - - [20/Aug/2021 21:21:06] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO werkzeug2021-08-20 21:21:12,593 : 192.168.1.154 - - [20/Aug/2021 21:21:12] "GET /create HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:21:12,841 : 192.168.1.154 - - [20/Aug/2021 21:21:12] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 21:21:19,407 : The Index page is retrieved
 INFO werkzeug2021-08-20 21:21:19,455 : 192.168.1.154 - - [20/Aug/2021 21:21:19] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:21:19,543 : 192.168.1.154 - - [20/Aug/2021 21:21:19] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
 INFO app2021-08-20 21:21:27,081 : Metrics request successfull
 INFO werkzeug2021-08-20 21:21:27,129 : 192.168.1.154 - - [20/Aug/2021 21:21:27] "GET /metrics HTTP/1.1" 200 -
 INFO app2021-08-20 21:21:40,895 : Healthz request successfull
 INFO werkzeug2021-08-20 21:21:40,967 : 192.168.1.154 - - [20/Aug/2021 21:21:40] "GET /healthz HTTP/1.1" 200 -
 INFO app2021-08-20 21:21:52,908 : The Index page is retrieved
 INFO werkzeug2021-08-20 21:21:52,964 : 192.168.1.154 - - [20/Aug/2021 21:21:52] "GET / HTTP/1.1" 200 -
 INFO werkzeug2021-08-20 21:21:53,084 : 192.168.1.154 - - [20/Aug/2021 21:21:53] "[36mGET /static/css/main.css HTTP/1.1[0m" 304 -
